name: Bandit Security Scan

on:
  schedule:
    - cron: '*/10 * * * 0' # Runs every 10 minutes on Sunday
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  bandit-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Use any Python 3.x version

    - name: Install Bandit
      run: |
        python -m pip install --upgrade pip
        pip install bandit

    - name: Run Bandit
      run: |
        bandit -r . -f txt -o bandit-report.txt
        cat bandit-report.txt

    - name: Upload Bandit Report
      uses: actions/upload-artifact@v3
      with:
        name: bandit-report
        path: bandit-report.txt
